### ISSUE TITLE
Restart Project

### ISSUE THREAD

**Issue by Trendy73** [ArjanteMarvelde/uSDR-pico#26]
Hello, Arjan. Are you planning to restart the project and add waterfall to it?

**Comment by ArjanteMarvelde** [comment]
Yes, I'm busy with a next version. The PCBs are about finished, save for some sanity checks and maybe some last minute changes.
Waterfall might be nice, but not a goal in itself. The uSDR-Pico design really is narrow-banded, so it wouldn't add a lot as such. Otherwise I would need to make the filtering more wideband, change the mixer and IF circuits, and have a whole new signal processing philosophy.
But you can take a look at Klaus Fensterseifer adaptations: https://github.com/kaefe64/Arduino_uSDX_Pico_FFT_Proj

**Comment by Trendy73** [comment]
OK, I understand. Good luck with your work, 73.
